language: node_js
node_js:
- stable
dist: trusty
sudo: required
before_script:
- npm install -g @angular/cli
script:
- npm run lint
- npm run build-prod
after_script:
  -
deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_TOKEN
  on:
    repo: cade-onibus/cade-onibus-backend
    branch: development
notifications:
  email: false
