language: node_js
node_js:
  - stable
dist: trusty
sudo: required
branches:
  only:
    - development
before_script:
  - npm install -g @angular/cli
script:
  - npm rum lint
  - npm rum build-prod
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github-token: $GITHUB_TOKEN
  on:
    branch: development
