language: node_js
node_js:
- '10.15.1'
dist: trusty
sudo: required
before_script:
- npm install -g @angular/cli
script:
- npm run lint
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_TOKEN
  on:
    repo: cade-onibus/cade-onibus-frontend
    branch: development
after_deploy:
  - echo "URL -> https://cade-onibus-2.firebaseapp.com"
notifications:
  email: false
